### ISSUE TITLE
root模式打完mod无法打开

### ISSUE THREAD

**Issue by naloder** [xausky/UnityModManager#8]
java.lang.RuntimeException: Unable to instantiate application com.excelliance.open.LBApplication: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.AssetManager android.content.res.Resources.getAssets()' on a null object reference
	at android.app.LoadedApk.makeApplication(LoadedApk.java:589)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5065)
	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360)
	at android.app.ActivityThread.handleBindApplication(<Xposed>)
	at android.app.ActivityThread.access$1600(ActivityThread.java:181)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1657)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5889)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1019)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:814)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.AssetManager android.content.res.Resources.getAssets()' on a null object reference
	at android.app.ContextImpl.getAssets(ContextImpl.java:927)
	at com.excelliance.lbsdk.base.j.a(Unknown Source)
	at com.excelliance.lbsdk.base.j.init(Unknown Source)
	at com.excelliance.lbsdk.LBSdkHelper.attachBaseContext(Unknown Source)
	at com.excelliance.open.LBApplication.attachBaseContext(LBApplication.java:82)
	at android.app.Application.attach(Application.java:181)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1008)
	at android.app.Instrumentation.newApplication(Instrumentation.java:992)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:584)
	... 14 more

**Comment by naloder** [comment]
另外虚拟环境模式下还是也有bug有些正常打入的补丁无法显示安装成功，都是显示安装失败以后，强行停止app然后才能打开
